// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	xxxarr "github.com/clambin/mediaclients/xxxarr"
)

// RadarrAPI is an autogenerated mock type for the RadarrAPI type
type RadarrAPI struct {
	mock.Mock
}

type RadarrAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *RadarrAPI) EXPECT() *RadarrAPI_Expecter {
	return &RadarrAPI_Expecter{mock: &_m.Mock}
}

// GetCalendar provides a mock function with given fields: ctx
func (_m *RadarrAPI) GetCalendar(ctx context.Context) ([]xxxarr.RadarrCalendarResponse, error) {
	ret := _m.Called(ctx)

	var r0 []xxxarr.RadarrCalendarResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]xxxarr.RadarrCalendarResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []xxxarr.RadarrCalendarResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]xxxarr.RadarrCalendarResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RadarrAPI_GetCalendar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCalendar'
type RadarrAPI_GetCalendar_Call struct {
	*mock.Call
}

// GetCalendar is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RadarrAPI_Expecter) GetCalendar(ctx interface{}) *RadarrAPI_GetCalendar_Call {
	return &RadarrAPI_GetCalendar_Call{Call: _e.mock.On("GetCalendar", ctx)}
}

func (_c *RadarrAPI_GetCalendar_Call) Run(run func(ctx context.Context)) *RadarrAPI_GetCalendar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RadarrAPI_GetCalendar_Call) Return(response []xxxarr.RadarrCalendarResponse, err error) *RadarrAPI_GetCalendar_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *RadarrAPI_GetCalendar_Call) RunAndReturn(run func(context.Context) ([]xxxarr.RadarrCalendarResponse, error)) *RadarrAPI_GetCalendar_Call {
	_c.Call.Return(run)
	return _c
}

// GetHealth provides a mock function with given fields: ctx
func (_m *RadarrAPI) GetHealth(ctx context.Context) ([]xxxarr.RadarrHealthResponse, error) {
	ret := _m.Called(ctx)

	var r0 []xxxarr.RadarrHealthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]xxxarr.RadarrHealthResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []xxxarr.RadarrHealthResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]xxxarr.RadarrHealthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RadarrAPI_GetHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealth'
type RadarrAPI_GetHealth_Call struct {
	*mock.Call
}

// GetHealth is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RadarrAPI_Expecter) GetHealth(ctx interface{}) *RadarrAPI_GetHealth_Call {
	return &RadarrAPI_GetHealth_Call{Call: _e.mock.On("GetHealth", ctx)}
}

func (_c *RadarrAPI_GetHealth_Call) Run(run func(ctx context.Context)) *RadarrAPI_GetHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RadarrAPI_GetHealth_Call) Return(response []xxxarr.RadarrHealthResponse, err error) *RadarrAPI_GetHealth_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *RadarrAPI_GetHealth_Call) RunAndReturn(run func(context.Context) ([]xxxarr.RadarrHealthResponse, error)) *RadarrAPI_GetHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetMovieByID provides a mock function with given fields: ctx, movieID
func (_m *RadarrAPI) GetMovieByID(ctx context.Context, movieID int) (xxxarr.RadarrMovieResponse, error) {
	ret := _m.Called(ctx, movieID)

	var r0 xxxarr.RadarrMovieResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (xxxarr.RadarrMovieResponse, error)); ok {
		return rf(ctx, movieID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) xxxarr.RadarrMovieResponse); ok {
		r0 = rf(ctx, movieID)
	} else {
		r0 = ret.Get(0).(xxxarr.RadarrMovieResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, movieID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RadarrAPI_GetMovieByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovieByID'
type RadarrAPI_GetMovieByID_Call struct {
	*mock.Call
}

// GetMovieByID is a helper method to define mock.On call
//   - ctx context.Context
//   - movieID int
func (_e *RadarrAPI_Expecter) GetMovieByID(ctx interface{}, movieID interface{}) *RadarrAPI_GetMovieByID_Call {
	return &RadarrAPI_GetMovieByID_Call{Call: _e.mock.On("GetMovieByID", ctx, movieID)}
}

func (_c *RadarrAPI_GetMovieByID_Call) Run(run func(ctx context.Context, movieID int)) *RadarrAPI_GetMovieByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *RadarrAPI_GetMovieByID_Call) Return(response xxxarr.RadarrMovieResponse, err error) *RadarrAPI_GetMovieByID_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *RadarrAPI_GetMovieByID_Call) RunAndReturn(run func(context.Context, int) (xxxarr.RadarrMovieResponse, error)) *RadarrAPI_GetMovieByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMovies provides a mock function with given fields: ctx
func (_m *RadarrAPI) GetMovies(ctx context.Context) ([]xxxarr.RadarrMovieResponse, error) {
	ret := _m.Called(ctx)

	var r0 []xxxarr.RadarrMovieResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]xxxarr.RadarrMovieResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []xxxarr.RadarrMovieResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]xxxarr.RadarrMovieResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RadarrAPI_GetMovies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovies'
type RadarrAPI_GetMovies_Call struct {
	*mock.Call
}

// GetMovies is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RadarrAPI_Expecter) GetMovies(ctx interface{}) *RadarrAPI_GetMovies_Call {
	return &RadarrAPI_GetMovies_Call{Call: _e.mock.On("GetMovies", ctx)}
}

func (_c *RadarrAPI_GetMovies_Call) Run(run func(ctx context.Context)) *RadarrAPI_GetMovies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RadarrAPI_GetMovies_Call) Return(response []xxxarr.RadarrMovieResponse, err error) *RadarrAPI_GetMovies_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *RadarrAPI_GetMovies_Call) RunAndReturn(run func(context.Context) ([]xxxarr.RadarrMovieResponse, error)) *RadarrAPI_GetMovies_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueue provides a mock function with given fields: ctx
func (_m *RadarrAPI) GetQueue(ctx context.Context) (xxxarr.RadarrQueueResponse, error) {
	ret := _m.Called(ctx)

	var r0 xxxarr.RadarrQueueResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (xxxarr.RadarrQueueResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) xxxarr.RadarrQueueResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(xxxarr.RadarrQueueResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RadarrAPI_GetQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueue'
type RadarrAPI_GetQueue_Call struct {
	*mock.Call
}

// GetQueue is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RadarrAPI_Expecter) GetQueue(ctx interface{}) *RadarrAPI_GetQueue_Call {
	return &RadarrAPI_GetQueue_Call{Call: _e.mock.On("GetQueue", ctx)}
}

func (_c *RadarrAPI_GetQueue_Call) Run(run func(ctx context.Context)) *RadarrAPI_GetQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RadarrAPI_GetQueue_Call) Return(response xxxarr.RadarrQueueResponse, err error) *RadarrAPI_GetQueue_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *RadarrAPI_GetQueue_Call) RunAndReturn(run func(context.Context) (xxxarr.RadarrQueueResponse, error)) *RadarrAPI_GetQueue_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueuePage provides a mock function with given fields: ctx, pageNr
func (_m *RadarrAPI) GetQueuePage(ctx context.Context, pageNr int) (xxxarr.RadarrQueueResponse, error) {
	ret := _m.Called(ctx, pageNr)

	var r0 xxxarr.RadarrQueueResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (xxxarr.RadarrQueueResponse, error)); ok {
		return rf(ctx, pageNr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) xxxarr.RadarrQueueResponse); ok {
		r0 = rf(ctx, pageNr)
	} else {
		r0 = ret.Get(0).(xxxarr.RadarrQueueResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, pageNr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RadarrAPI_GetQueuePage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueuePage'
type RadarrAPI_GetQueuePage_Call struct {
	*mock.Call
}

// GetQueuePage is a helper method to define mock.On call
//   - ctx context.Context
//   - pageNr int
func (_e *RadarrAPI_Expecter) GetQueuePage(ctx interface{}, pageNr interface{}) *RadarrAPI_GetQueuePage_Call {
	return &RadarrAPI_GetQueuePage_Call{Call: _e.mock.On("GetQueuePage", ctx, pageNr)}
}

func (_c *RadarrAPI_GetQueuePage_Call) Run(run func(ctx context.Context, pageNr int)) *RadarrAPI_GetQueuePage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *RadarrAPI_GetQueuePage_Call) Return(response xxxarr.RadarrQueueResponse, err error) *RadarrAPI_GetQueuePage_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *RadarrAPI_GetQueuePage_Call) RunAndReturn(run func(context.Context, int) (xxxarr.RadarrQueueResponse, error)) *RadarrAPI_GetQueuePage_Call {
	_c.Call.Return(run)
	return _c
}

// GetSystemStatus provides a mock function with given fields: ctx
func (_m *RadarrAPI) GetSystemStatus(ctx context.Context) (xxxarr.RadarrSystemStatusResponse, error) {
	ret := _m.Called(ctx)

	var r0 xxxarr.RadarrSystemStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (xxxarr.RadarrSystemStatusResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) xxxarr.RadarrSystemStatusResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(xxxarr.RadarrSystemStatusResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RadarrAPI_GetSystemStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSystemStatus'
type RadarrAPI_GetSystemStatus_Call struct {
	*mock.Call
}

// GetSystemStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RadarrAPI_Expecter) GetSystemStatus(ctx interface{}) *RadarrAPI_GetSystemStatus_Call {
	return &RadarrAPI_GetSystemStatus_Call{Call: _e.mock.On("GetSystemStatus", ctx)}
}

func (_c *RadarrAPI_GetSystemStatus_Call) Run(run func(ctx context.Context)) *RadarrAPI_GetSystemStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RadarrAPI_GetSystemStatus_Call) Return(response xxxarr.RadarrSystemStatusResponse, err error) *RadarrAPI_GetSystemStatus_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *RadarrAPI_GetSystemStatus_Call) RunAndReturn(run func(context.Context) (xxxarr.RadarrSystemStatusResponse, error)) *RadarrAPI_GetSystemStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function with given fields:
func (_m *RadarrAPI) GetURL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RadarrAPI_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type RadarrAPI_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
func (_e *RadarrAPI_Expecter) GetURL() *RadarrAPI_GetURL_Call {
	return &RadarrAPI_GetURL_Call{Call: _e.mock.On("GetURL")}
}

func (_c *RadarrAPI_GetURL_Call) Run(run func()) *RadarrAPI_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RadarrAPI_GetURL_Call) Return(url string) *RadarrAPI_GetURL_Call {
	_c.Call.Return(url)
	return _c
}

func (_c *RadarrAPI_GetURL_Call) RunAndReturn(run func() string) *RadarrAPI_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewRadarrAPI creates a new instance of RadarrAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRadarrAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *RadarrAPI {
	mock := &RadarrAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
