// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	transmission "github.com/clambin/mediaclients/transmission"
	mock "github.com/stretchr/testify/mock"
)

// API is an autogenerated mock type for the API type
type API struct {
	mock.Mock
}

// GetSessionParameters provides a mock function with given fields: ctx
func (_m *API) GetSessionParameters(ctx context.Context) (transmission.SessionParameters, error) {
	ret := _m.Called(ctx)

	var r0 transmission.SessionParameters
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (transmission.SessionParameters, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) transmission.SessionParameters); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(transmission.SessionParameters)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSessionStatistics provides a mock function with given fields: ctx
func (_m *API) GetSessionStatistics(ctx context.Context) (transmission.SessionStats, error) {
	ret := _m.Called(ctx)

	var r0 transmission.SessionStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (transmission.SessionStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) transmission.SessionStats); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(transmission.SessionStats)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAPI creates a new instance of API. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *API {
	mock := &API{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
