// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	transmission "github.com/clambin/mediaclients/transmission"
	mock "github.com/stretchr/testify/mock"
)

// Getter is an autogenerated mock type for the Getter type
type Getter struct {
	mock.Mock
}

type Getter_Expecter struct {
	mock *mock.Mock
}

func (_m *Getter) EXPECT() *Getter_Expecter {
	return &Getter_Expecter{mock: &_m.Mock}
}

// GetSessionParameters provides a mock function with given fields: ctx
func (_m *Getter) GetSessionParameters(ctx context.Context) (transmission.SessionParameters, error) {
	ret := _m.Called(ctx)

	var r0 transmission.SessionParameters
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (transmission.SessionParameters, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) transmission.SessionParameters); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(transmission.SessionParameters)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Getter_GetSessionParameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionParameters'
type Getter_GetSessionParameters_Call struct {
	*mock.Call
}

// GetSessionParameters is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Getter_Expecter) GetSessionParameters(ctx interface{}) *Getter_GetSessionParameters_Call {
	return &Getter_GetSessionParameters_Call{Call: _e.mock.On("GetSessionParameters", ctx)}
}

func (_c *Getter_GetSessionParameters_Call) Run(run func(ctx context.Context)) *Getter_GetSessionParameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Getter_GetSessionParameters_Call) Return(_a0 transmission.SessionParameters, _a1 error) *Getter_GetSessionParameters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Getter_GetSessionParameters_Call) RunAndReturn(run func(context.Context) (transmission.SessionParameters, error)) *Getter_GetSessionParameters_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionStatistics provides a mock function with given fields: ctx
func (_m *Getter) GetSessionStatistics(ctx context.Context) (transmission.SessionStats, error) {
	ret := _m.Called(ctx)

	var r0 transmission.SessionStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (transmission.SessionStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) transmission.SessionStats); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(transmission.SessionStats)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Getter_GetSessionStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionStatistics'
type Getter_GetSessionStatistics_Call struct {
	*mock.Call
}

// GetSessionStatistics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Getter_Expecter) GetSessionStatistics(ctx interface{}) *Getter_GetSessionStatistics_Call {
	return &Getter_GetSessionStatistics_Call{Call: _e.mock.On("GetSessionStatistics", ctx)}
}

func (_c *Getter_GetSessionStatistics_Call) Run(run func(ctx context.Context)) *Getter_GetSessionStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Getter_GetSessionStatistics_Call) Return(stats transmission.SessionStats, err error) *Getter_GetSessionStatistics_Call {
	_c.Call.Return(stats, err)
	return _c
}

func (_c *Getter_GetSessionStatistics_Call) RunAndReturn(run func(context.Context) (transmission.SessionStats, error)) *Getter_GetSessionStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetter creates a new instance of Getter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Getter {
	mock := &Getter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
