apiVersion: apps/v1
kind: Deployment
metadata:
  name: github.com/clambin/mediamon
  namespace: media
  labels:
    app: github.com/clambin/mediamon
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github.com/clambin/mediamon
  template:
    metadata:
      labels:
        app: github.com/clambin/mediamon
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: github.com/clambin/mediamon
        image: clambin/github.com/clambin/mediamon:develop
        imagePullPolicy: Always
        args:
        - -f=/etc/github.com/clambin/mediamon/github.com/clambin/mediamon.yml
        volumeMounts:
        - name: github.com/clambin/mediamon-config
          mountPath: "/etc/github.com/clambin/mediamon"
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            memory: 40Mi
      volumes:
        - name: github.com/clambin/mediamon-config
          configMap:
            name: github.com/clambin/mediamon-config