// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	plex "github.com/clambin/mediaclients/plex"
	mock "github.com/stretchr/testify/mock"
)

// Getter is an autogenerated mock type for the Getter type
type Getter struct {
	mock.Mock
}

type Getter_Expecter struct {
	mock *mock.Mock
}

func (_m *Getter) EXPECT() *Getter_Expecter {
	return &Getter_Expecter{mock: &_m.Mock}
}

// GetIdentity provides a mock function with given fields: _a0
func (_m *Getter) GetIdentity(_a0 context.Context) (plex.Identity, error) {
	ret := _m.Called(_a0)

	var r0 plex.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (plex.Identity, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) plex.Identity); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(plex.Identity)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Getter_GetIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIdentity'
type Getter_GetIdentity_Call struct {
	*mock.Call
}

// GetIdentity is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Getter_Expecter) GetIdentity(_a0 interface{}) *Getter_GetIdentity_Call {
	return &Getter_GetIdentity_Call{Call: _e.mock.On("GetIdentity", _a0)}
}

func (_c *Getter_GetIdentity_Call) Run(run func(_a0 context.Context)) *Getter_GetIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Getter_GetIdentity_Call) Return(_a0 plex.Identity, _a1 error) *Getter_GetIdentity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Getter_GetIdentity_Call) RunAndReturn(run func(context.Context) (plex.Identity, error)) *Getter_GetIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessions provides a mock function with given fields: _a0
func (_m *Getter) GetSessions(_a0 context.Context) (plex.Sessions, error) {
	ret := _m.Called(_a0)

	var r0 plex.Sessions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (plex.Sessions, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) plex.Sessions); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(plex.Sessions)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Getter_GetSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessions'
type Getter_GetSessions_Call struct {
	*mock.Call
}

// GetSessions is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Getter_Expecter) GetSessions(_a0 interface{}) *Getter_GetSessions_Call {
	return &Getter_GetSessions_Call{Call: _e.mock.On("GetSessions", _a0)}
}

func (_c *Getter_GetSessions_Call) Run(run func(_a0 context.Context)) *Getter_GetSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Getter_GetSessions_Call) Return(_a0 plex.Sessions, _a1 error) *Getter_GetSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Getter_GetSessions_Call) RunAndReturn(run func(context.Context) (plex.Sessions, error)) *Getter_GetSessions_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetter creates a new instance of Getter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Getter {
	mock := &Getter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
