with-expecter: true
filename: "{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/clambin/mediamon/v2/internal/collectors/plex:
    interfaces:
      API:
      IPLocator:
  github.com/clambin/mediamon/v2/internal/collectors/transmission:
    interfaces:
      API:
  github.com/clambin/mediamon/v2/internal/collectors/xxxarr:
    interfaces:
      Scraper:
  github.com/clambin/mediamon/v2/internal/collectors/xxxarr/scraper:
    interfaces:
      RadarrAPI:
      SonarrAPI:
