dir: '{{.InterfaceDir}}/mocks'
structname: '{{.InterfaceName}}'
pkgname: mocks
filename: mocks.go
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/clambin/mediamon/v2/internal/collectors/xxxarr:
    interfaces:
      Client: {}
  github.com/clambin/mediamon/v2/internal/collectors/xxxarr/clients:
    interfaces:
      RadarrClient: {}
      SonarrClient: {}
