{
 "title": "Media Server",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "OpenVPN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VPN Uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(openvpn_client_status)", "legendFormat": "On" }
   ]
  },
  {
   "title": "OpenVPN Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(openvpn_client_tcp_udp_read_bytes_total[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "-avg(rate(openvpn_client_tcp_udp_write_bytes_total[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "OpenVPN Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "targets": [
    { "expr": "sum(openvpn_client_status)", "legendFormat": "On" },
    { "expr": "1-sum(openvpn_client_status)", "legendFormat": "Off" }
   ]
  },
  { "title": "Transmission", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Transmission version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mediamon_transmission_version{version=~\"[0-9]+.[0-9]+.*\"}"
    }
   ]
  },
  {
   "title": "Transmission Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(mediamon_transmission_download_speed)",
     "legendFormat": "Download"
    },
    {
     "expr": "-sum(mediamon_transmission_upload_speed)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Torrents",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mediamon_transmission_active_torrent_count)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(mediamon_transmission_paused_torrent_count)",
     "legendFormat": "Paused"
    }
   ]
  },
  { "title": "Sonarr / Radarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Sonarr version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mediamon_xxxarr_version{application=\"sonarr\"}"
    }
   ]
  },
  {
   "title": "Download Queue",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mediamon_xxxarr_queued_count) by (application)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "On Calendar",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mediamon_xxxarr_calendar_count) by (application)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Not monitored",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mediamon_xxxarr_unmonitored_count) by (application)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Monitoring",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mediamon_xxxarr_monitored_count) by (application)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Radarr version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mediamon_xxxarr_version{application=\"radarr\"}"
    }
   ]
  },
  { "title": "Plex", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Plex version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mediamon_plex_version" }
   ]
  },
  {
   "title": "Plex sessions",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (user) (mediamon_plex_session_count)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Plex bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"plex-.*\"}[5m]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "-sum(rate(container_network_receive_bytes_total{pod=~\"plex-.*\"}[5m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Plex transcoders",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (mediamon_plex_transcoder_type_count)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum(mediamon_plex_transcoder_encoding_count)",
     "legendFormat": "encoding"
    },
    {
     "expr": "sum(mediamon_plex_transcoder_speed_total)",
     "legendFormat": "speed"
    }
   ]
  },
  {
   "title": "Plex CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{container=\"plex\"}[2m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{container=\"plex\"}[2m]))",
     "legendFormat": "user"
    }
   ]
  }
 ]
}