{
 "title": "mediamon - internal",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (application, request) (\n    rate (mediamon_request_duration_seconds_sum[5m]) / rate (mediamon_request_duration_seconds_count[5m])\n)",
     "legendFormat": "{{application}} - {{request}}"
    }
   ]
  },
  {
   "title": "API calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by (application, request) (\n    rate (mediamon_request_duration_seconds_count[5m])\n)",
     "legendFormat": "{{application}} - {{request}}"
    }
   ]
  },
  {
   "title": "API errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (application, request) (increase(mediamon_request_errors_total[5m]))",
     "legendFormat": "{{application}} - {{request}}"
    }
   ]
  }
 ]
}