// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/clambin/mediamon/v2/internal/collectors/xxxarr/clients"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetCalendar provides a mock function for the type Client
func (_mock *Client) GetCalendar(context1 context.Context, n int) ([]string, error) {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for GetCalendar")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]string, error)); ok {
		return returnFunc(context1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = returnFunc(context1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(context1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetCalendar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCalendar'
type Client_GetCalendar_Call struct {
	*mock.Call
}

// GetCalendar is a helper method to define mock.On call
//   - context1 context.Context
//   - n int
func (_e *Client_Expecter) GetCalendar(context1 interface{}, n interface{}) *Client_GetCalendar_Call {
	return &Client_GetCalendar_Call{Call: _e.mock.On("GetCalendar", context1, n)}
}

func (_c *Client_GetCalendar_Call) Run(run func(context1 context.Context, n int)) *Client_GetCalendar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetCalendar_Call) Return(strings []string, err error) *Client_GetCalendar_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Client_GetCalendar_Call) RunAndReturn(run func(context1 context.Context, n int) ([]string, error)) *Client_GetCalendar_Call {
	_c.Call.Return(run)
	return _c
}

// GetHealth provides a mock function for the type Client
func (_mock *Client) GetHealth(context1 context.Context) (map[string]int, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetHealth")
	}

	var r0 map[string]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]int, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]int); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealth'
type Client_GetHealth_Call struct {
	*mock.Call
}

// GetHealth is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Client_Expecter) GetHealth(context1 interface{}) *Client_GetHealth_Call {
	return &Client_GetHealth_Call{Call: _e.mock.On("GetHealth", context1)}
}

func (_c *Client_GetHealth_Call) Run(run func(context1 context.Context)) *Client_GetHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_GetHealth_Call) Return(stringToInt map[string]int, err error) *Client_GetHealth_Call {
	_c.Call.Return(stringToInt, err)
	return _c
}

func (_c *Client_GetHealth_Call) RunAndReturn(run func(context1 context.Context) (map[string]int, error)) *Client_GetHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetLibrary provides a mock function for the type Client
func (_mock *Client) GetLibrary(context1 context.Context) (clients.Library, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetLibrary")
	}

	var r0 clients.Library
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (clients.Library, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) clients.Library); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(clients.Library)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetLibrary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLibrary'
type Client_GetLibrary_Call struct {
	*mock.Call
}

// GetLibrary is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Client_Expecter) GetLibrary(context1 interface{}) *Client_GetLibrary_Call {
	return &Client_GetLibrary_Call{Call: _e.mock.On("GetLibrary", context1)}
}

func (_c *Client_GetLibrary_Call) Run(run func(context1 context.Context)) *Client_GetLibrary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_GetLibrary_Call) Return(library clients.Library, err error) *Client_GetLibrary_Call {
	_c.Call.Return(library, err)
	return _c
}

func (_c *Client_GetLibrary_Call) RunAndReturn(run func(context1 context.Context) (clients.Library, error)) *Client_GetLibrary_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueue provides a mock function for the type Client
func (_mock *Client) GetQueue(context1 context.Context) ([]clients.QueuedItem, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetQueue")
	}

	var r0 []clients.QueuedItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]clients.QueuedItem, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []clients.QueuedItem); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]clients.QueuedItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueue'
type Client_GetQueue_Call struct {
	*mock.Call
}

// GetQueue is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Client_Expecter) GetQueue(context1 interface{}) *Client_GetQueue_Call {
	return &Client_GetQueue_Call{Call: _e.mock.On("GetQueue", context1)}
}

func (_c *Client_GetQueue_Call) Run(run func(context1 context.Context)) *Client_GetQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_GetQueue_Call) Return(queuedItems []clients.QueuedItem, err error) *Client_GetQueue_Call {
	_c.Call.Return(queuedItems, err)
	return _c
}

func (_c *Client_GetQueue_Call) RunAndReturn(run func(context1 context.Context) ([]clients.QueuedItem, error)) *Client_GetQueue_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function for the type Client
func (_mock *Client) GetVersion(context1 context.Context) (string, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type Client_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Client_Expecter) GetVersion(context1 interface{}) *Client_GetVersion_Call {
	return &Client_GetVersion_Call{Call: _e.mock.On("GetVersion", context1)}
}

func (_c *Client_GetVersion_Call) Run(run func(context1 context.Context)) *Client_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_GetVersion_Call) Return(s string, err error) *Client_GetVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Client_GetVersion_Call) RunAndReturn(run func(context1 context.Context) (string, error)) *Client_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}
