{
 "title": "Media Server",
 "tags": [ "grope" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "user",
    "query": {
     "query": "label_values(mediamon_plex_session_count,user)"
    }
   }
  ]
 },
 "panels": [
  { "title": "OpenVPN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VPN Uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(openvpn_client_status)", "legendFormat": "On" }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(openvpn_client_tcp_udp_read_bytes_total[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "-avg(rate(openvpn_client_tcp_udp_write_bytes_total[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "VPN Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 1 },
   "targets": [
    { "expr": "avg(openvpn_client_status)", "legendFormat": "On" },
    { "expr": "1-avg(openvpn_client_status)", "legendFormat": "Off" }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "increase(k8s_restarter_restarted_pods_total{name=\"transmission\",namespace=\"media\"}[$__rate_interval])"
    }
   ]
  },
  { "title": "Transmission", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Transmission version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mediamon_transmission_version{version=~\"[0-9]+.[0-9]+.*\"}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(mediamon_transmission_download_speed)",
     "legendFormat": "Download"
    },
    {
     "expr": "-sum(mediamon_transmission_upload_speed)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Torrents",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mediamon_transmission_active_torrent_count)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(mediamon_transmission_paused_torrent_count)",
     "legendFormat": "Paused"
    }
   ]
  },
  {
   "title": "temp disk space",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"pvc-nfs-provisioner-2-nfs-subdir-external-provisioner\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"pvc-nfs-provisioner-2-nfs-subdir-external-provisioner\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "media disk space",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{job=\"kubernetes-api-servers\",persistentvolumeclaim=~\"video.*\"} / kubelet_volume_stats_capacity_bytes{job=\"kubernetes-api-servers\",persistentvolumeclaim=~\"video.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "Sonarr / Radarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Sonarr version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mediamon_xxxarr_version{application=\"sonarr\"}"
    }
   ]
  },
  {
   "title": "On Calendar",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "mediamon_xxxarr_calendar", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Media",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application) (mediamon_xxxarr_unmonitored_count)",
     "legendFormat": "{{application}} - unmonitored"
    },
    {
     "expr": "sum by (application) (mediamon_xxxarr_monitored_count)",
     "legendFormat": "{{application}} - monitored"
    }
   ]
  },
  {
   "title": "Radarr version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mediamon_xxxarr_version{application=\"radarr\"}"
    }
   ]
  },
  {
   "title": "Downloading",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "mediamon_xxxarr_queued_downloaded_bytes / mediamon_xxxarr_queued_total_bytes",
     "legendFormat": "{{server}}"
    }
   ]
  },
  { "title": "Plex", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Plex version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mediamon_plex_version" }
   ]
  },
  {
   "title": "Current sessions",
   "type": "table",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (title, user, player, mode, videoCodec, location) (mediamon_plex_session_count{user=~\"^$user$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All sessions w/in timeframe",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (title, user, player, mode, videoCodec, location) (mediamon_plex_session_count{user=~\"^$user$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sessions by users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (user) (mediamon_plex_session_count{user=~\"^$user$\"})",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{container=\"plex\"}[$__rate_interval]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{container=\"plex\"}[$__rate_interval]))",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 3, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "sum by (user) (mediamon_plex_session_bandwidth{user=~\"^$user$\"})",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "GPU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (engine) (gpumon_engine_usage{attrib=\"busy\"})",
     "legendFormat": "{{engine}}"
    }
   ]
  },
  {
   "title": "Sessions by location",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 3, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (location) (mediamon_plex_session_count)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"plex-.*\"}[$__rate_interval]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "-sum(rate(container_network_receive_bytes_total{pod=~\"plex-.*\"}[$__rate_interval]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Plex transcoders",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 3, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (state) (mediamon_plex_transcoder_count)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(mediamon_plex_transcoder_speed)",
     "legendFormat": "Speed"
    }
   ]
  },
  {
   "title": "Remote Users",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 9, "x": 15, "y": 55 },
   "targets": [
    {
     "expr": "sum by (user, lon, lat) (mediamon_plex_session_count{location!=\"lan\",user=~\"^$user$\"})"
    }
   ]
  },
  {
   "title": "Library Sizes (bytes)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (url, library) (mediamon_plex_library_bytes)",
     "legendFormat": "{{library}}"
    }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mediamon_plex_movie_count)", "legendFormat": "{{library}}" }
   ]
  },
  {
   "title": "Shows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(mediamon_plex_show_count)", "legendFormat": "{{library}}" }
   ]
  },
  {
   "title": "Episodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mediamon_plex_episode_count)",
     "legendFormat": "{{library}}"
    }
   ]
  }
 ]
}
{
 "title": "mediamon - internal",
 "tags": [ "grope" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "application",
    "query": {
     "query": "label_values(mediamon_http_requests_total,application)"
    }
   }
  ]
 },
 "panels": [
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(mediamon_http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (application) (mediamon_http_request_duration_seconds_sum / mediamon_http_request_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "application" },
  {
   "title": "request rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by (code) (\n    rate (mediamon_http_requests_total{application=~\"$application\"}[$__rate_interval])\n)",
     "legendFormat": " {{code}}"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (path) (\n    mediamon_http_request_duration_seconds_sum{application=~\"$application\"} / mediamon_http_request_duration_seconds_count\n)",
     "legendFormat": "{{application}} - {{path}}"
    }
   ]
  }
 ]
}
{
 "title": "Prowlarr",
 "tags": [ "grope" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Indexer response times",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (indexer) (mediamon_prowlarr_indexer_response_time)",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  {
   "title": "Queries by Indexer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": " sum by (indexer)(rate(mediamon_prowlarr_indexer_query_total[$__rate_interval]))",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  {
   "title": "Grabs by Indexer",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (indexer) (mediamon_prowlarr_indexer_grab_total)",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  {
   "title": "query errors by indexer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (indexer) (mediamon_prowlarr_indexer_failed_query_total / mediamon_prowlarr_indexer_query_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "grab errors by indexer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (indexer) (mediamon_prowlarr_indexer_failed_grab_total / mediamon_prowlarr_indexer_grab_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by User Agent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "sum by (user_agent) (rate(mediamon_prowlarr_user_agent_query_total[$__rate_interval]))",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "Grabs by User Agent",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (user_agent) (mediamon_prowlarr_user_agent_grab_total)",
     "legendFormat": "{{user_agent}}"
    }
   ]
  }
 ]
}