// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	scraper "github.com/clambin/mediamon/collectors/xxxarr/scraper"
	mock "github.com/stretchr/testify/mock"
)

// Scraper is an autogenerated mock type for the Scraper type
type Scraper struct {
	mock.Mock
}

// Scrape provides a mock function with given fields:
func (_m *Scraper) Scrape() (scraper.Stats, error) {
	ret := _m.Called()

	var r0 scraper.Stats
	if rf, ok := ret.Get(0).(func() scraper.Stats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(scraper.Stats)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewScraper creates a new instance of Scraper. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewScraper(t testing.TB) *Scraper {
	mock := &Scraper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
