// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/clambin/mediaclients/radarr"
	"github.com/clambin/mediaclients/sonarr"
	mock "github.com/stretchr/testify/mock"
)

// NewRadarrClient creates a new instance of RadarrClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRadarrClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RadarrClient {
	mock := &RadarrClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RadarrClient is an autogenerated mock type for the RadarrClient type
type RadarrClient struct {
	mock.Mock
}

type RadarrClient_Expecter struct {
	mock *mock.Mock
}

func (_m *RadarrClient) EXPECT() *RadarrClient_Expecter {
	return &RadarrClient_Expecter{mock: &_m.Mock}
}

// GetApiV3CalendarWithResponse provides a mock function for the type RadarrClient
func (_mock *RadarrClient) GetApiV3CalendarWithResponse(ctx context.Context, params *radarr.GetApiV3CalendarParams, reqEditors ...radarr.RequestEditorFn) (*radarr.GetApiV3CalendarResponse, error) {
	// radarr.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV3CalendarWithResponse")
	}

	var r0 *radarr.GetApiV3CalendarResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *radarr.GetApiV3CalendarParams, ...radarr.RequestEditorFn) (*radarr.GetApiV3CalendarResponse, error)); ok {
		return returnFunc(ctx, params, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *radarr.GetApiV3CalendarParams, ...radarr.RequestEditorFn) *radarr.GetApiV3CalendarResponse); ok {
		r0 = returnFunc(ctx, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*radarr.GetApiV3CalendarResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *radarr.GetApiV3CalendarParams, ...radarr.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RadarrClient_GetApiV3CalendarWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV3CalendarWithResponse'
type RadarrClient_GetApiV3CalendarWithResponse_Call struct {
	*mock.Call
}

// GetApiV3CalendarWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - params *radarr.GetApiV3CalendarParams
//   - reqEditors ...radarr.RequestEditorFn
func (_e *RadarrClient_Expecter) GetApiV3CalendarWithResponse(ctx interface{}, params interface{}, reqEditors ...interface{}) *RadarrClient_GetApiV3CalendarWithResponse_Call {
	return &RadarrClient_GetApiV3CalendarWithResponse_Call{Call: _e.mock.On("GetApiV3CalendarWithResponse",
		append([]interface{}{ctx, params}, reqEditors...)...)}
}

func (_c *RadarrClient_GetApiV3CalendarWithResponse_Call) Run(run func(ctx context.Context, params *radarr.GetApiV3CalendarParams, reqEditors ...radarr.RequestEditorFn)) *RadarrClient_GetApiV3CalendarWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *radarr.GetApiV3CalendarParams
		if args[1] != nil {
			arg1 = args[1].(*radarr.GetApiV3CalendarParams)
		}
		var arg2 []radarr.RequestEditorFn
		variadicArgs := make([]radarr.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(radarr.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RadarrClient_GetApiV3CalendarWithResponse_Call) Return(getApiV3CalendarResponse *radarr.GetApiV3CalendarResponse, err error) *RadarrClient_GetApiV3CalendarWithResponse_Call {
	_c.Call.Return(getApiV3CalendarResponse, err)
	return _c
}

func (_c *RadarrClient_GetApiV3CalendarWithResponse_Call) RunAndReturn(run func(ctx context.Context, params *radarr.GetApiV3CalendarParams, reqEditors ...radarr.RequestEditorFn) (*radarr.GetApiV3CalendarResponse, error)) *RadarrClient_GetApiV3CalendarWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiV3HealthWithResponse provides a mock function for the type RadarrClient
func (_mock *RadarrClient) GetApiV3HealthWithResponse(ctx context.Context, reqEditors ...radarr.RequestEditorFn) (*radarr.GetApiV3HealthResponse, error) {
	// radarr.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV3HealthWithResponse")
	}

	var r0 *radarr.GetApiV3HealthResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...radarr.RequestEditorFn) (*radarr.GetApiV3HealthResponse, error)); ok {
		return returnFunc(ctx, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...radarr.RequestEditorFn) *radarr.GetApiV3HealthResponse); ok {
		r0 = returnFunc(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*radarr.GetApiV3HealthResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...radarr.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RadarrClient_GetApiV3HealthWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV3HealthWithResponse'
type RadarrClient_GetApiV3HealthWithResponse_Call struct {
	*mock.Call
}

// GetApiV3HealthWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...radarr.RequestEditorFn
func (_e *RadarrClient_Expecter) GetApiV3HealthWithResponse(ctx interface{}, reqEditors ...interface{}) *RadarrClient_GetApiV3HealthWithResponse_Call {
	return &RadarrClient_GetApiV3HealthWithResponse_Call{Call: _e.mock.On("GetApiV3HealthWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *RadarrClient_GetApiV3HealthWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...radarr.RequestEditorFn)) *RadarrClient_GetApiV3HealthWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []radarr.RequestEditorFn
		variadicArgs := make([]radarr.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(radarr.RequestEditorFn)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *RadarrClient_GetApiV3HealthWithResponse_Call) Return(getApiV3HealthResponse *radarr.GetApiV3HealthResponse, err error) *RadarrClient_GetApiV3HealthWithResponse_Call {
	_c.Call.Return(getApiV3HealthResponse, err)
	return _c
}

func (_c *RadarrClient_GetApiV3HealthWithResponse_Call) RunAndReturn(run func(ctx context.Context, reqEditors ...radarr.RequestEditorFn) (*radarr.GetApiV3HealthResponse, error)) *RadarrClient_GetApiV3HealthWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiV3MovieWithResponse provides a mock function for the type RadarrClient
func (_mock *RadarrClient) GetApiV3MovieWithResponse(ctx context.Context, params *radarr.GetApiV3MovieParams, reqEditors ...radarr.RequestEditorFn) (*radarr.GetApiV3MovieResponse, error) {
	// radarr.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV3MovieWithResponse")
	}

	var r0 *radarr.GetApiV3MovieResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *radarr.GetApiV3MovieParams, ...radarr.RequestEditorFn) (*radarr.GetApiV3MovieResponse, error)); ok {
		return returnFunc(ctx, params, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *radarr.GetApiV3MovieParams, ...radarr.RequestEditorFn) *radarr.GetApiV3MovieResponse); ok {
		r0 = returnFunc(ctx, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*radarr.GetApiV3MovieResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *radarr.GetApiV3MovieParams, ...radarr.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RadarrClient_GetApiV3MovieWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV3MovieWithResponse'
type RadarrClient_GetApiV3MovieWithResponse_Call struct {
	*mock.Call
}

// GetApiV3MovieWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - params *radarr.GetApiV3MovieParams
//   - reqEditors ...radarr.RequestEditorFn
func (_e *RadarrClient_Expecter) GetApiV3MovieWithResponse(ctx interface{}, params interface{}, reqEditors ...interface{}) *RadarrClient_GetApiV3MovieWithResponse_Call {
	return &RadarrClient_GetApiV3MovieWithResponse_Call{Call: _e.mock.On("GetApiV3MovieWithResponse",
		append([]interface{}{ctx, params}, reqEditors...)...)}
}

func (_c *RadarrClient_GetApiV3MovieWithResponse_Call) Run(run func(ctx context.Context, params *radarr.GetApiV3MovieParams, reqEditors ...radarr.RequestEditorFn)) *RadarrClient_GetApiV3MovieWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *radarr.GetApiV3MovieParams
		if args[1] != nil {
			arg1 = args[1].(*radarr.GetApiV3MovieParams)
		}
		var arg2 []radarr.RequestEditorFn
		variadicArgs := make([]radarr.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(radarr.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RadarrClient_GetApiV3MovieWithResponse_Call) Return(getApiV3MovieResponse *radarr.GetApiV3MovieResponse, err error) *RadarrClient_GetApiV3MovieWithResponse_Call {
	_c.Call.Return(getApiV3MovieResponse, err)
	return _c
}

func (_c *RadarrClient_GetApiV3MovieWithResponse_Call) RunAndReturn(run func(ctx context.Context, params *radarr.GetApiV3MovieParams, reqEditors ...radarr.RequestEditorFn) (*radarr.GetApiV3MovieResponse, error)) *RadarrClient_GetApiV3MovieWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiV3QueueWithResponse provides a mock function for the type RadarrClient
func (_mock *RadarrClient) GetApiV3QueueWithResponse(ctx context.Context, params *radarr.GetApiV3QueueParams, reqEditors ...radarr.RequestEditorFn) (*radarr.GetApiV3QueueResponse, error) {
	// radarr.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV3QueueWithResponse")
	}

	var r0 *radarr.GetApiV3QueueResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *radarr.GetApiV3QueueParams, ...radarr.RequestEditorFn) (*radarr.GetApiV3QueueResponse, error)); ok {
		return returnFunc(ctx, params, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *radarr.GetApiV3QueueParams, ...radarr.RequestEditorFn) *radarr.GetApiV3QueueResponse); ok {
		r0 = returnFunc(ctx, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*radarr.GetApiV3QueueResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *radarr.GetApiV3QueueParams, ...radarr.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RadarrClient_GetApiV3QueueWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV3QueueWithResponse'
type RadarrClient_GetApiV3QueueWithResponse_Call struct {
	*mock.Call
}

// GetApiV3QueueWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - params *radarr.GetApiV3QueueParams
//   - reqEditors ...radarr.RequestEditorFn
func (_e *RadarrClient_Expecter) GetApiV3QueueWithResponse(ctx interface{}, params interface{}, reqEditors ...interface{}) *RadarrClient_GetApiV3QueueWithResponse_Call {
	return &RadarrClient_GetApiV3QueueWithResponse_Call{Call: _e.mock.On("GetApiV3QueueWithResponse",
		append([]interface{}{ctx, params}, reqEditors...)...)}
}

func (_c *RadarrClient_GetApiV3QueueWithResponse_Call) Run(run func(ctx context.Context, params *radarr.GetApiV3QueueParams, reqEditors ...radarr.RequestEditorFn)) *RadarrClient_GetApiV3QueueWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *radarr.GetApiV3QueueParams
		if args[1] != nil {
			arg1 = args[1].(*radarr.GetApiV3QueueParams)
		}
		var arg2 []radarr.RequestEditorFn
		variadicArgs := make([]radarr.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(radarr.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RadarrClient_GetApiV3QueueWithResponse_Call) Return(getApiV3QueueResponse *radarr.GetApiV3QueueResponse, err error) *RadarrClient_GetApiV3QueueWithResponse_Call {
	_c.Call.Return(getApiV3QueueResponse, err)
	return _c
}

func (_c *RadarrClient_GetApiV3QueueWithResponse_Call) RunAndReturn(run func(ctx context.Context, params *radarr.GetApiV3QueueParams, reqEditors ...radarr.RequestEditorFn) (*radarr.GetApiV3QueueResponse, error)) *RadarrClient_GetApiV3QueueWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiV3SystemStatusWithResponse provides a mock function for the type RadarrClient
func (_mock *RadarrClient) GetApiV3SystemStatusWithResponse(ctx context.Context, reqEditors ...radarr.RequestEditorFn) (*radarr.GetApiV3SystemStatusResponse, error) {
	// radarr.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV3SystemStatusWithResponse")
	}

	var r0 *radarr.GetApiV3SystemStatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...radarr.RequestEditorFn) (*radarr.GetApiV3SystemStatusResponse, error)); ok {
		return returnFunc(ctx, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...radarr.RequestEditorFn) *radarr.GetApiV3SystemStatusResponse); ok {
		r0 = returnFunc(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*radarr.GetApiV3SystemStatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...radarr.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RadarrClient_GetApiV3SystemStatusWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV3SystemStatusWithResponse'
type RadarrClient_GetApiV3SystemStatusWithResponse_Call struct {
	*mock.Call
}

// GetApiV3SystemStatusWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...radarr.RequestEditorFn
func (_e *RadarrClient_Expecter) GetApiV3SystemStatusWithResponse(ctx interface{}, reqEditors ...interface{}) *RadarrClient_GetApiV3SystemStatusWithResponse_Call {
	return &RadarrClient_GetApiV3SystemStatusWithResponse_Call{Call: _e.mock.On("GetApiV3SystemStatusWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *RadarrClient_GetApiV3SystemStatusWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...radarr.RequestEditorFn)) *RadarrClient_GetApiV3SystemStatusWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []radarr.RequestEditorFn
		variadicArgs := make([]radarr.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(radarr.RequestEditorFn)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *RadarrClient_GetApiV3SystemStatusWithResponse_Call) Return(getApiV3SystemStatusResponse *radarr.GetApiV3SystemStatusResponse, err error) *RadarrClient_GetApiV3SystemStatusWithResponse_Call {
	_c.Call.Return(getApiV3SystemStatusResponse, err)
	return _c
}

func (_c *RadarrClient_GetApiV3SystemStatusWithResponse_Call) RunAndReturn(run func(ctx context.Context, reqEditors ...radarr.RequestEditorFn) (*radarr.GetApiV3SystemStatusResponse, error)) *RadarrClient_GetApiV3SystemStatusWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewSonarrClient creates a new instance of SonarrClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSonarrClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SonarrClient {
	mock := &SonarrClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SonarrClient is an autogenerated mock type for the SonarrClient type
type SonarrClient struct {
	mock.Mock
}

type SonarrClient_Expecter struct {
	mock *mock.Mock
}

func (_m *SonarrClient) EXPECT() *SonarrClient_Expecter {
	return &SonarrClient_Expecter{mock: &_m.Mock}
}

// GetApiV3CalendarWithResponse provides a mock function for the type SonarrClient
func (_mock *SonarrClient) GetApiV3CalendarWithResponse(ctx context.Context, params *sonarr.GetApiV3CalendarParams, reqEditors ...sonarr.RequestEditorFn) (*sonarr.GetApiV3CalendarResponse, error) {
	// sonarr.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV3CalendarWithResponse")
	}

	var r0 *sonarr.GetApiV3CalendarResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sonarr.GetApiV3CalendarParams, ...sonarr.RequestEditorFn) (*sonarr.GetApiV3CalendarResponse, error)); ok {
		return returnFunc(ctx, params, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sonarr.GetApiV3CalendarParams, ...sonarr.RequestEditorFn) *sonarr.GetApiV3CalendarResponse); ok {
		r0 = returnFunc(ctx, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonarr.GetApiV3CalendarResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sonarr.GetApiV3CalendarParams, ...sonarr.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SonarrClient_GetApiV3CalendarWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV3CalendarWithResponse'
type SonarrClient_GetApiV3CalendarWithResponse_Call struct {
	*mock.Call
}

// GetApiV3CalendarWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sonarr.GetApiV3CalendarParams
//   - reqEditors ...sonarr.RequestEditorFn
func (_e *SonarrClient_Expecter) GetApiV3CalendarWithResponse(ctx interface{}, params interface{}, reqEditors ...interface{}) *SonarrClient_GetApiV3CalendarWithResponse_Call {
	return &SonarrClient_GetApiV3CalendarWithResponse_Call{Call: _e.mock.On("GetApiV3CalendarWithResponse",
		append([]interface{}{ctx, params}, reqEditors...)...)}
}

func (_c *SonarrClient_GetApiV3CalendarWithResponse_Call) Run(run func(ctx context.Context, params *sonarr.GetApiV3CalendarParams, reqEditors ...sonarr.RequestEditorFn)) *SonarrClient_GetApiV3CalendarWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sonarr.GetApiV3CalendarParams
		if args[1] != nil {
			arg1 = args[1].(*sonarr.GetApiV3CalendarParams)
		}
		var arg2 []sonarr.RequestEditorFn
		variadicArgs := make([]sonarr.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(sonarr.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SonarrClient_GetApiV3CalendarWithResponse_Call) Return(getApiV3CalendarResponse *sonarr.GetApiV3CalendarResponse, err error) *SonarrClient_GetApiV3CalendarWithResponse_Call {
	_c.Call.Return(getApiV3CalendarResponse, err)
	return _c
}

func (_c *SonarrClient_GetApiV3CalendarWithResponse_Call) RunAndReturn(run func(ctx context.Context, params *sonarr.GetApiV3CalendarParams, reqEditors ...sonarr.RequestEditorFn) (*sonarr.GetApiV3CalendarResponse, error)) *SonarrClient_GetApiV3CalendarWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiV3HealthWithResponse provides a mock function for the type SonarrClient
func (_mock *SonarrClient) GetApiV3HealthWithResponse(ctx context.Context, reqEditors ...sonarr.RequestEditorFn) (*sonarr.GetApiV3HealthResponse, error) {
	// sonarr.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV3HealthWithResponse")
	}

	var r0 *sonarr.GetApiV3HealthResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...sonarr.RequestEditorFn) (*sonarr.GetApiV3HealthResponse, error)); ok {
		return returnFunc(ctx, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...sonarr.RequestEditorFn) *sonarr.GetApiV3HealthResponse); ok {
		r0 = returnFunc(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonarr.GetApiV3HealthResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...sonarr.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SonarrClient_GetApiV3HealthWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV3HealthWithResponse'
type SonarrClient_GetApiV3HealthWithResponse_Call struct {
	*mock.Call
}

// GetApiV3HealthWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...sonarr.RequestEditorFn
func (_e *SonarrClient_Expecter) GetApiV3HealthWithResponse(ctx interface{}, reqEditors ...interface{}) *SonarrClient_GetApiV3HealthWithResponse_Call {
	return &SonarrClient_GetApiV3HealthWithResponse_Call{Call: _e.mock.On("GetApiV3HealthWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *SonarrClient_GetApiV3HealthWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...sonarr.RequestEditorFn)) *SonarrClient_GetApiV3HealthWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []sonarr.RequestEditorFn
		variadicArgs := make([]sonarr.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(sonarr.RequestEditorFn)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *SonarrClient_GetApiV3HealthWithResponse_Call) Return(getApiV3HealthResponse *sonarr.GetApiV3HealthResponse, err error) *SonarrClient_GetApiV3HealthWithResponse_Call {
	_c.Call.Return(getApiV3HealthResponse, err)
	return _c
}

func (_c *SonarrClient_GetApiV3HealthWithResponse_Call) RunAndReturn(run func(ctx context.Context, reqEditors ...sonarr.RequestEditorFn) (*sonarr.GetApiV3HealthResponse, error)) *SonarrClient_GetApiV3HealthWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiV3QueueWithResponse provides a mock function for the type SonarrClient
func (_mock *SonarrClient) GetApiV3QueueWithResponse(ctx context.Context, params *sonarr.GetApiV3QueueParams, reqEditors ...sonarr.RequestEditorFn) (*sonarr.GetApiV3QueueResponse, error) {
	// sonarr.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV3QueueWithResponse")
	}

	var r0 *sonarr.GetApiV3QueueResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sonarr.GetApiV3QueueParams, ...sonarr.RequestEditorFn) (*sonarr.GetApiV3QueueResponse, error)); ok {
		return returnFunc(ctx, params, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sonarr.GetApiV3QueueParams, ...sonarr.RequestEditorFn) *sonarr.GetApiV3QueueResponse); ok {
		r0 = returnFunc(ctx, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonarr.GetApiV3QueueResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sonarr.GetApiV3QueueParams, ...sonarr.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SonarrClient_GetApiV3QueueWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV3QueueWithResponse'
type SonarrClient_GetApiV3QueueWithResponse_Call struct {
	*mock.Call
}

// GetApiV3QueueWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sonarr.GetApiV3QueueParams
//   - reqEditors ...sonarr.RequestEditorFn
func (_e *SonarrClient_Expecter) GetApiV3QueueWithResponse(ctx interface{}, params interface{}, reqEditors ...interface{}) *SonarrClient_GetApiV3QueueWithResponse_Call {
	return &SonarrClient_GetApiV3QueueWithResponse_Call{Call: _e.mock.On("GetApiV3QueueWithResponse",
		append([]interface{}{ctx, params}, reqEditors...)...)}
}

func (_c *SonarrClient_GetApiV3QueueWithResponse_Call) Run(run func(ctx context.Context, params *sonarr.GetApiV3QueueParams, reqEditors ...sonarr.RequestEditorFn)) *SonarrClient_GetApiV3QueueWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sonarr.GetApiV3QueueParams
		if args[1] != nil {
			arg1 = args[1].(*sonarr.GetApiV3QueueParams)
		}
		var arg2 []sonarr.RequestEditorFn
		variadicArgs := make([]sonarr.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(sonarr.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SonarrClient_GetApiV3QueueWithResponse_Call) Return(getApiV3QueueResponse *sonarr.GetApiV3QueueResponse, err error) *SonarrClient_GetApiV3QueueWithResponse_Call {
	_c.Call.Return(getApiV3QueueResponse, err)
	return _c
}

func (_c *SonarrClient_GetApiV3QueueWithResponse_Call) RunAndReturn(run func(ctx context.Context, params *sonarr.GetApiV3QueueParams, reqEditors ...sonarr.RequestEditorFn) (*sonarr.GetApiV3QueueResponse, error)) *SonarrClient_GetApiV3QueueWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiV3SeriesWithResponse provides a mock function for the type SonarrClient
func (_mock *SonarrClient) GetApiV3SeriesWithResponse(ctx context.Context, params *sonarr.GetApiV3SeriesParams, reqEditors ...sonarr.RequestEditorFn) (*sonarr.GetApiV3SeriesResponse, error) {
	// sonarr.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV3SeriesWithResponse")
	}

	var r0 *sonarr.GetApiV3SeriesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sonarr.GetApiV3SeriesParams, ...sonarr.RequestEditorFn) (*sonarr.GetApiV3SeriesResponse, error)); ok {
		return returnFunc(ctx, params, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sonarr.GetApiV3SeriesParams, ...sonarr.RequestEditorFn) *sonarr.GetApiV3SeriesResponse); ok {
		r0 = returnFunc(ctx, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonarr.GetApiV3SeriesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sonarr.GetApiV3SeriesParams, ...sonarr.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SonarrClient_GetApiV3SeriesWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV3SeriesWithResponse'
type SonarrClient_GetApiV3SeriesWithResponse_Call struct {
	*mock.Call
}

// GetApiV3SeriesWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sonarr.GetApiV3SeriesParams
//   - reqEditors ...sonarr.RequestEditorFn
func (_e *SonarrClient_Expecter) GetApiV3SeriesWithResponse(ctx interface{}, params interface{}, reqEditors ...interface{}) *SonarrClient_GetApiV3SeriesWithResponse_Call {
	return &SonarrClient_GetApiV3SeriesWithResponse_Call{Call: _e.mock.On("GetApiV3SeriesWithResponse",
		append([]interface{}{ctx, params}, reqEditors...)...)}
}

func (_c *SonarrClient_GetApiV3SeriesWithResponse_Call) Run(run func(ctx context.Context, params *sonarr.GetApiV3SeriesParams, reqEditors ...sonarr.RequestEditorFn)) *SonarrClient_GetApiV3SeriesWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sonarr.GetApiV3SeriesParams
		if args[1] != nil {
			arg1 = args[1].(*sonarr.GetApiV3SeriesParams)
		}
		var arg2 []sonarr.RequestEditorFn
		variadicArgs := make([]sonarr.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(sonarr.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SonarrClient_GetApiV3SeriesWithResponse_Call) Return(getApiV3SeriesResponse *sonarr.GetApiV3SeriesResponse, err error) *SonarrClient_GetApiV3SeriesWithResponse_Call {
	_c.Call.Return(getApiV3SeriesResponse, err)
	return _c
}

func (_c *SonarrClient_GetApiV3SeriesWithResponse_Call) RunAndReturn(run func(ctx context.Context, params *sonarr.GetApiV3SeriesParams, reqEditors ...sonarr.RequestEditorFn) (*sonarr.GetApiV3SeriesResponse, error)) *SonarrClient_GetApiV3SeriesWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiV3SystemStatusWithResponse provides a mock function for the type SonarrClient
func (_mock *SonarrClient) GetApiV3SystemStatusWithResponse(ctx context.Context, reqEditors ...sonarr.RequestEditorFn) (*sonarr.GetApiV3SystemStatusResponse, error) {
	// sonarr.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV3SystemStatusWithResponse")
	}

	var r0 *sonarr.GetApiV3SystemStatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...sonarr.RequestEditorFn) (*sonarr.GetApiV3SystemStatusResponse, error)); ok {
		return returnFunc(ctx, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...sonarr.RequestEditorFn) *sonarr.GetApiV3SystemStatusResponse); ok {
		r0 = returnFunc(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonarr.GetApiV3SystemStatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...sonarr.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SonarrClient_GetApiV3SystemStatusWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV3SystemStatusWithResponse'
type SonarrClient_GetApiV3SystemStatusWithResponse_Call struct {
	*mock.Call
}

// GetApiV3SystemStatusWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...sonarr.RequestEditorFn
func (_e *SonarrClient_Expecter) GetApiV3SystemStatusWithResponse(ctx interface{}, reqEditors ...interface{}) *SonarrClient_GetApiV3SystemStatusWithResponse_Call {
	return &SonarrClient_GetApiV3SystemStatusWithResponse_Call{Call: _e.mock.On("GetApiV3SystemStatusWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *SonarrClient_GetApiV3SystemStatusWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...sonarr.RequestEditorFn)) *SonarrClient_GetApiV3SystemStatusWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []sonarr.RequestEditorFn
		variadicArgs := make([]sonarr.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(sonarr.RequestEditorFn)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *SonarrClient_GetApiV3SystemStatusWithResponse_Call) Return(getApiV3SystemStatusResponse *sonarr.GetApiV3SystemStatusResponse, err error) *SonarrClient_GetApiV3SystemStatusWithResponse_Call {
	_c.Call.Return(getApiV3SystemStatusResponse, err)
	return _c
}

func (_c *SonarrClient_GetApiV3SystemStatusWithResponse_Call) RunAndReturn(run func(ctx context.Context, reqEditors ...sonarr.RequestEditorFn) (*sonarr.GetApiV3SystemStatusResponse, error)) *SonarrClient_GetApiV3SystemStatusWithResponse_Call {
	_c.Call.Return(run)
	return _c
}
