// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	sonarr "github.com/clambin/mediaclients/sonarr"
	mock "github.com/stretchr/testify/mock"
)

// SonarrClient is an autogenerated mock type for the SonarrClient type
type SonarrClient struct {
	mock.Mock
}

type SonarrClient_Expecter struct {
	mock *mock.Mock
}

func (_m *SonarrClient) EXPECT() *SonarrClient_Expecter {
	return &SonarrClient_Expecter{mock: &_m.Mock}
}

// GetApiV3CalendarWithResponse provides a mock function with given fields: ctx, params, reqEditors
func (_m *SonarrClient) GetApiV3CalendarWithResponse(ctx context.Context, params *sonarr.GetApiV3CalendarParams, reqEditors ...sonarr.RequestEditorFn) (*sonarr.GetApiV3CalendarResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV3CalendarWithResponse")
	}

	var r0 *sonarr.GetApiV3CalendarResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sonarr.GetApiV3CalendarParams, ...sonarr.RequestEditorFn) (*sonarr.GetApiV3CalendarResponse, error)); ok {
		return rf(ctx, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sonarr.GetApiV3CalendarParams, ...sonarr.RequestEditorFn) *sonarr.GetApiV3CalendarResponse); ok {
		r0 = rf(ctx, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonarr.GetApiV3CalendarResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sonarr.GetApiV3CalendarParams, ...sonarr.RequestEditorFn) error); ok {
		r1 = rf(ctx, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SonarrClient_GetApiV3CalendarWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV3CalendarWithResponse'
type SonarrClient_GetApiV3CalendarWithResponse_Call struct {
	*mock.Call
}

// GetApiV3CalendarWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sonarr.GetApiV3CalendarParams
//   - reqEditors ...sonarr.RequestEditorFn
func (_e *SonarrClient_Expecter) GetApiV3CalendarWithResponse(ctx interface{}, params interface{}, reqEditors ...interface{}) *SonarrClient_GetApiV3CalendarWithResponse_Call {
	return &SonarrClient_GetApiV3CalendarWithResponse_Call{Call: _e.mock.On("GetApiV3CalendarWithResponse",
		append([]interface{}{ctx, params}, reqEditors...)...)}
}

func (_c *SonarrClient_GetApiV3CalendarWithResponse_Call) Run(run func(ctx context.Context, params *sonarr.GetApiV3CalendarParams, reqEditors ...sonarr.RequestEditorFn)) *SonarrClient_GetApiV3CalendarWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]sonarr.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(sonarr.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(*sonarr.GetApiV3CalendarParams), variadicArgs...)
	})
	return _c
}

func (_c *SonarrClient_GetApiV3CalendarWithResponse_Call) Return(_a0 *sonarr.GetApiV3CalendarResponse, _a1 error) *SonarrClient_GetApiV3CalendarWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SonarrClient_GetApiV3CalendarWithResponse_Call) RunAndReturn(run func(context.Context, *sonarr.GetApiV3CalendarParams, ...sonarr.RequestEditorFn) (*sonarr.GetApiV3CalendarResponse, error)) *SonarrClient_GetApiV3CalendarWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiV3HealthWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *SonarrClient) GetApiV3HealthWithResponse(ctx context.Context, reqEditors ...sonarr.RequestEditorFn) (*sonarr.GetApiV3HealthResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV3HealthWithResponse")
	}

	var r0 *sonarr.GetApiV3HealthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...sonarr.RequestEditorFn) (*sonarr.GetApiV3HealthResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...sonarr.RequestEditorFn) *sonarr.GetApiV3HealthResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonarr.GetApiV3HealthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...sonarr.RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SonarrClient_GetApiV3HealthWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV3HealthWithResponse'
type SonarrClient_GetApiV3HealthWithResponse_Call struct {
	*mock.Call
}

// GetApiV3HealthWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...sonarr.RequestEditorFn
func (_e *SonarrClient_Expecter) GetApiV3HealthWithResponse(ctx interface{}, reqEditors ...interface{}) *SonarrClient_GetApiV3HealthWithResponse_Call {
	return &SonarrClient_GetApiV3HealthWithResponse_Call{Call: _e.mock.On("GetApiV3HealthWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *SonarrClient_GetApiV3HealthWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...sonarr.RequestEditorFn)) *SonarrClient_GetApiV3HealthWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]sonarr.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(sonarr.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *SonarrClient_GetApiV3HealthWithResponse_Call) Return(_a0 *sonarr.GetApiV3HealthResponse, _a1 error) *SonarrClient_GetApiV3HealthWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SonarrClient_GetApiV3HealthWithResponse_Call) RunAndReturn(run func(context.Context, ...sonarr.RequestEditorFn) (*sonarr.GetApiV3HealthResponse, error)) *SonarrClient_GetApiV3HealthWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiV3QueueWithResponse provides a mock function with given fields: ctx, params, reqEditors
func (_m *SonarrClient) GetApiV3QueueWithResponse(ctx context.Context, params *sonarr.GetApiV3QueueParams, reqEditors ...sonarr.RequestEditorFn) (*sonarr.GetApiV3QueueResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV3QueueWithResponse")
	}

	var r0 *sonarr.GetApiV3QueueResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sonarr.GetApiV3QueueParams, ...sonarr.RequestEditorFn) (*sonarr.GetApiV3QueueResponse, error)); ok {
		return rf(ctx, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sonarr.GetApiV3QueueParams, ...sonarr.RequestEditorFn) *sonarr.GetApiV3QueueResponse); ok {
		r0 = rf(ctx, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonarr.GetApiV3QueueResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sonarr.GetApiV3QueueParams, ...sonarr.RequestEditorFn) error); ok {
		r1 = rf(ctx, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SonarrClient_GetApiV3QueueWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV3QueueWithResponse'
type SonarrClient_GetApiV3QueueWithResponse_Call struct {
	*mock.Call
}

// GetApiV3QueueWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sonarr.GetApiV3QueueParams
//   - reqEditors ...sonarr.RequestEditorFn
func (_e *SonarrClient_Expecter) GetApiV3QueueWithResponse(ctx interface{}, params interface{}, reqEditors ...interface{}) *SonarrClient_GetApiV3QueueWithResponse_Call {
	return &SonarrClient_GetApiV3QueueWithResponse_Call{Call: _e.mock.On("GetApiV3QueueWithResponse",
		append([]interface{}{ctx, params}, reqEditors...)...)}
}

func (_c *SonarrClient_GetApiV3QueueWithResponse_Call) Run(run func(ctx context.Context, params *sonarr.GetApiV3QueueParams, reqEditors ...sonarr.RequestEditorFn)) *SonarrClient_GetApiV3QueueWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]sonarr.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(sonarr.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(*sonarr.GetApiV3QueueParams), variadicArgs...)
	})
	return _c
}

func (_c *SonarrClient_GetApiV3QueueWithResponse_Call) Return(_a0 *sonarr.GetApiV3QueueResponse, _a1 error) *SonarrClient_GetApiV3QueueWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SonarrClient_GetApiV3QueueWithResponse_Call) RunAndReturn(run func(context.Context, *sonarr.GetApiV3QueueParams, ...sonarr.RequestEditorFn) (*sonarr.GetApiV3QueueResponse, error)) *SonarrClient_GetApiV3QueueWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiV3SeriesWithResponse provides a mock function with given fields: ctx, params, reqEditors
func (_m *SonarrClient) GetApiV3SeriesWithResponse(ctx context.Context, params *sonarr.GetApiV3SeriesParams, reqEditors ...sonarr.RequestEditorFn) (*sonarr.GetApiV3SeriesResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV3SeriesWithResponse")
	}

	var r0 *sonarr.GetApiV3SeriesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sonarr.GetApiV3SeriesParams, ...sonarr.RequestEditorFn) (*sonarr.GetApiV3SeriesResponse, error)); ok {
		return rf(ctx, params, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sonarr.GetApiV3SeriesParams, ...sonarr.RequestEditorFn) *sonarr.GetApiV3SeriesResponse); ok {
		r0 = rf(ctx, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonarr.GetApiV3SeriesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sonarr.GetApiV3SeriesParams, ...sonarr.RequestEditorFn) error); ok {
		r1 = rf(ctx, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SonarrClient_GetApiV3SeriesWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV3SeriesWithResponse'
type SonarrClient_GetApiV3SeriesWithResponse_Call struct {
	*mock.Call
}

// GetApiV3SeriesWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sonarr.GetApiV3SeriesParams
//   - reqEditors ...sonarr.RequestEditorFn
func (_e *SonarrClient_Expecter) GetApiV3SeriesWithResponse(ctx interface{}, params interface{}, reqEditors ...interface{}) *SonarrClient_GetApiV3SeriesWithResponse_Call {
	return &SonarrClient_GetApiV3SeriesWithResponse_Call{Call: _e.mock.On("GetApiV3SeriesWithResponse",
		append([]interface{}{ctx, params}, reqEditors...)...)}
}

func (_c *SonarrClient_GetApiV3SeriesWithResponse_Call) Run(run func(ctx context.Context, params *sonarr.GetApiV3SeriesParams, reqEditors ...sonarr.RequestEditorFn)) *SonarrClient_GetApiV3SeriesWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]sonarr.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(sonarr.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(*sonarr.GetApiV3SeriesParams), variadicArgs...)
	})
	return _c
}

func (_c *SonarrClient_GetApiV3SeriesWithResponse_Call) Return(_a0 *sonarr.GetApiV3SeriesResponse, _a1 error) *SonarrClient_GetApiV3SeriesWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SonarrClient_GetApiV3SeriesWithResponse_Call) RunAndReturn(run func(context.Context, *sonarr.GetApiV3SeriesParams, ...sonarr.RequestEditorFn) (*sonarr.GetApiV3SeriesResponse, error)) *SonarrClient_GetApiV3SeriesWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiV3SystemStatusWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *SonarrClient) GetApiV3SystemStatusWithResponse(ctx context.Context, reqEditors ...sonarr.RequestEditorFn) (*sonarr.GetApiV3SystemStatusResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV3SystemStatusWithResponse")
	}

	var r0 *sonarr.GetApiV3SystemStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...sonarr.RequestEditorFn) (*sonarr.GetApiV3SystemStatusResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...sonarr.RequestEditorFn) *sonarr.GetApiV3SystemStatusResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sonarr.GetApiV3SystemStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...sonarr.RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SonarrClient_GetApiV3SystemStatusWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV3SystemStatusWithResponse'
type SonarrClient_GetApiV3SystemStatusWithResponse_Call struct {
	*mock.Call
}

// GetApiV3SystemStatusWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...sonarr.RequestEditorFn
func (_e *SonarrClient_Expecter) GetApiV3SystemStatusWithResponse(ctx interface{}, reqEditors ...interface{}) *SonarrClient_GetApiV3SystemStatusWithResponse_Call {
	return &SonarrClient_GetApiV3SystemStatusWithResponse_Call{Call: _e.mock.On("GetApiV3SystemStatusWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *SonarrClient_GetApiV3SystemStatusWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...sonarr.RequestEditorFn)) *SonarrClient_GetApiV3SystemStatusWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]sonarr.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(sonarr.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *SonarrClient_GetApiV3SystemStatusWithResponse_Call) Return(_a0 *sonarr.GetApiV3SystemStatusResponse, _a1 error) *SonarrClient_GetApiV3SystemStatusWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SonarrClient_GetApiV3SystemStatusWithResponse_Call) RunAndReturn(run func(context.Context, ...sonarr.RequestEditorFn) (*sonarr.GetApiV3SystemStatusResponse, error)) *SonarrClient_GetApiV3SystemStatusWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewSonarrClient creates a new instance of SonarrClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSonarrClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SonarrClient {
	mock := &SonarrClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
