// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	xxxarr "github.com/clambin/mediaclients/xxxarr"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetIndexStats provides a mock function with given fields: _a0
func (_m *Client) GetIndexStats(_a0 context.Context) (xxxarr.ProwlarrIndexersStats, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetIndexStats")
	}

	var r0 xxxarr.ProwlarrIndexersStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (xxxarr.ProwlarrIndexersStats, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) xxxarr.ProwlarrIndexersStats); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(xxxarr.ProwlarrIndexersStats)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetIndexStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIndexStats'
type Client_GetIndexStats_Call struct {
	*mock.Call
}

// GetIndexStats is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Client_Expecter) GetIndexStats(_a0 interface{}) *Client_GetIndexStats_Call {
	return &Client_GetIndexStats_Call{Call: _e.mock.On("GetIndexStats", _a0)}
}

func (_c *Client_GetIndexStats_Call) Run(run func(_a0 context.Context)) *Client_GetIndexStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Client_GetIndexStats_Call) Return(_a0 xxxarr.ProwlarrIndexersStats, _a1 error) *Client_GetIndexStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetIndexStats_Call) RunAndReturn(run func(context.Context) (xxxarr.ProwlarrIndexersStats, error)) *Client_GetIndexStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
