name: "Flake8"

on:
  push:
  pull_request:

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: flake8
        run: |
          pip install flake8
          flake8 --max-line-length 120