name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@v2
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@v2
    with:
      target: mediamon
  release:
    needs:
      - build
    uses: clambin/workflows/.github/workflows/release.yaml@v2

