name: "SAST"

on:
  push:
  pull_request:

jobs:
  sast:
    name: sast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: sast
        run: |
          pip install bandit safety
          safety check
          bandit -r -x ./tests .