name: Vulnerabilities

on:
  push:
  schedule:
    - cron: '23 3 * * 6'

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
  vulnerabilities:
    uses: clambin/workflows/.github/workflows/vulnerabilities.yaml@main
